### ISSUE TITLE
Only use half of the dataset？

### ISSUE THREAD

**Issue by Horizon-M** [v587su/SEC#1]
Hello, while attempting to reproduce this work, I observed that the dataset was split into two parts for saving during generation. 

However, it appears that only one half of the dataset was utilized in certain subsequent steps, such as during the training of the controller. The pertinent configuration settings can be found on line 44 of the `base_dataset.py` file.

I would appreciate an explanation for this configuration or if there has been an error on my part.

**Comment by v587su** [comment]
Hello, @Horizon-M

Thanks for your interest in this work. I use this to quickly test the effects of some changes. It is a temporary implementation. I forgot to change it back in the official code. Sorry for the confusion it caused. I'll fix it.

**Comment by Horizon-M** [comment]
I got it! Thanks for the reply, closing the issue.
